version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./mysql.env
    environment:
      # MYSQL_ROOT_PASSWORD should be specified in ./mysql.env
      MYSQL_USER: ghost
      # MYSQL_PASSWORD should be specified in ./mysql.env
      MYSQL_DATABASE: ghost_production
    volumes:
      - ../volumes/mysql/:/var/lib/mysql/

  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./ghost.env
    environment:
      url: https://beta.advisory.sg
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      # database__connection__password should be specified in ./ghost.env
      database__connection__database: ghost_production
      mail__transport: SMTP
      mail__options__service: MailJet
      mail__options__host: in-v3.mailjet.com
      mail__options__auth__user: 72678b19703f35a36d1b010a710d30ba
      # mail__options__auth__pass should be specified in ./ghost.env
      mail__options__port: 465
      mail__options__secureConnection: "true"
      # storage__active: s3
      # storage__s3__accessKeyId: AKIATZCBF3CWR3JPXC5G
      # # storage__s3__secretAccessKey should be specified in ./ghost.env
      # storage__s3__bucket: advisorysg-ghost
      # storage__s3__region: ap-southeast-1
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../volumes/ghost/content/:/var/lib/ghost/content/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # the nginx instance inherits the current existing letsencrypt setup
      # on the server
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/:ro
