version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: on-failure:3
    env_file:
      - ./mysql.env
    environment:
      # MYSQL_ROOT_PASSWORD should be specified in ./mysql.env
      MYSQL_USER: ghost
      # MYSQL_PASSWORD should be specified in ./mysql.env
      MYSQL_DATABASE: ghost_production
    volumes:
      - mysql-data:/var/lib/mysql/
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  ghost:
    image: ghost:latest
    restart: on-failure:3
    depends_on:
      - mysql
    env_file:
      - ./ghost.env
    environment:
      url: https://beta.advisory.sg
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      # database__connection__password should be specified in ./ghost.env
      database__connection__database: ghost_production
      mail__transport: SMTP
      mail__options__service: MailJet
      mail__options__host: in-v3.mailjet.com
      mail__options__auth__user: 72678b19703f35a36d1b010a710d30ba
      # mail__options__auth__pass should be specified in ./ghost.env
      mail__options__port: 465
      mail__options__secureConnection: "true"
      storage__active: s3
      storage__s3__accessKeyId: AKIATZCBF3CW4R3XZVHS
      # storage__s3__secretAccessKey should be specified in ./ghost.env
      storage__s3__bucket: advisorysg-ghost
      storage__s3__region: ap-southeast-1
    volumes:
      - ghost-content:/var/lib/ghost/content/

  nginx:
    image: nginx:latest
    restart: on-failure:3
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/usr/share/nginx/html

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/usr/share/nginx/html
    # command is only to be executed when creating new certificate
    command: certonly --non-interactive --webroot --webroot-path=/usr/share/nginx/html --email sysadmin@advisory.sg --agree-tos -d beta.advisory.sg
    profiles:
      - donotstart

  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:7.17.0
    restart: on-failure:3
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    env_file:
      - ./elastic-agent.env
    environment:
      # FLEET_ENROLLMENT_TOKEN should be specified in ./elastic-agent.env
      - FLEET_ENROLL=1
      - FLEET_URL=https://b64977688a1f4f61a610b68abbf534e9.fleet.ap-southeast-1.aws.found.io:443
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/usr/share/nginx/html

volumes:
  mysql-data:
  ghost-content:
  certbot-etc:
  certbot-var:
  certbot-webroot:
