version: "3"
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    env_file:
      - ./ghost.env
    environment:
      url: https://beta.advisory.sg
      database__client: mysql
      database__connection__host: ls-1965ed2806d44aa484935908cbdc5e1b6664dc90.ceyeqv4lsxnz.ap-southeast-1.rds.amazonaws.com
      database__connection__user: ghost
      # database__connection__password should be specified in ./ghost.env
      database__connection__database: ghost_production
      mail__transport: SMTP
      mail__options__service: MailJet
      mail__options__host: in-v3.mailjet.com
      mail__options__auth__user: 72678b19703f35a36d1b010a710d30ba
      # mail__options__auth__pass should be specified in ./ghost.env
      mail__options__port: 465
      mail__options__secureConnection: "true"
      storage__active: s3
      storage__s3__accessKeyId: AKIATZCBF3CW4R3XZVHS
      # storage__s3__secretAccessKey should be specified in ./ghost.env
      storage__s3__bucket: advisorysg-ghost
      storage__s3__region: ap-southeast-1
    volumes:
      - ghost-content:/var/lib/ghost/content/

  nginx:
    image: nginx:1-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/usr/share/nginx/html

  certbot:
    image: certbot/certbot:v2.5.0
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/usr/share/nginx/html
    # command is only to be executed when creating new certificate
    command: certonly --non-interactive --webroot --webroot-path=/usr/share/nginx/html --email sysadmin@advisory.sg --agree-tos --expand -d beta.advisory.sg -d umami.advisory.sg
    profiles:
      - donotstart

  umami:
    image: ghcr.io/umami-software/umami:mysql-latest
    restart: always
    env_file:
      - ./umami.env
    ports:
      - "3000:3000"
    environment:
      DATABASE_TYPE: MySQL

volumes:
  ghost-content:
  certbot-etc:
  certbot-var:
  certbot-webroot:
