services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=advisory.sg
      - VALIDATION=http
      - SUBDOMAINS=umami,
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./swag_config:/config
    ports:
      - 443:443
      - 80:80

  umami:
    image: docker.umami.is/umami-software/umami:postgresql-v2
    restart: always
    env_file:
      - ./umami.env
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami?connect_timeout=30
    ports:
      - "3000:3000"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  proxysql:
    image: proxysql/proxysql
    restart: always
    ports:
      - "3306:6033"
      #- "16032:6032" # Admin console
      #- "16033:6033"
      #- "16070:6070"
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro

