services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=advisory.sg
      - VALIDATION=http
      - SUBDOMAINS=beta,
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./swag_config:/config
    ports:
      - 443:443
      - 80:80

  ghost:
    image: ghost:5-alpine
    restart: always
    env_file:
      - ./ghost.env
    environment:
      url: https://beta.advisory.sg
      database__client: mysql
      database__connection__host: ls-37fc92a2ac6d2e89c8e72aa7bcdb6f197c6d1303.ceyeqv4lsxnz.ap-southeast-1.rds.amazonaws.com
      database__connection__user: ghost
      # database__connection__password should be specified in ./ghost.env
      database__connection__database: ghost_production
      mail__transport: SMTP
      mail__options__service: MailJet
      mail__options__host: in-v3.mailjet.com
      mail__options__auth__user: 72678b19703f35a36d1b010a710d30ba
      # mail__options__auth__pass should be specified in ./ghost.env
      mail__options__port: 465
      mail__options__secureConnection: "true"
      storage__active: s3
      storage__s3__accessKeyId: AKIATZCBF3CW4R3XZVHS
      # storage__s3__secretAccessKey should be specified in ./ghost.env
      storage__s3__bucket: advisorysg-ghost
      storage__s3__region: ap-southeast-1
    volumes:
      - content:/var/lib/ghost/content/

volumes:
  content:
