version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./mysql.env
    environment:
      MYSQL_USER: ghost
      MYSQL_DATABASE: ghost_production
    volumes:
      - ./volumes/mysql/:/var/lib/mysql/

  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./ghost.env
    environment:
      url: https://beta.advisory.sg
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__database: ghost_production
      mail__transport: SMTP
      mail__options__service: MailJet
      mail__options__host: in-v3.mailjet.com
      mail__options__port: 465
      mail__options__secureConnection: "true"
    volumes:
      - ./volumes/ghost/content/:/var/lib/ghost/content/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/
      - ./volumes/nginx/html/:/usr/share/nginx/html/
